name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install -e ".[test]"
      - name: Lint with ruff
        run: ruff check --output-format=github .
      - name: Lint with mypy
        run: mypy .
      - name: Test
        run: coverage run -m pytest -v
      - name: Verify coverage
        run: coverage report --fail-under=95
